### ISSUE TITLE
Error when using `distinct`

### ISSUE THREAD

**Issue by tiberiuana** [filhodanuvem/gitql#113]
`distinct` doesn't seem to work in Gitql 2.1.0 (binary release)

Using the example from the README:

**Query:**
```
select distinct author from commits where date < '2020-01-01'
```

**Error:**
```
Expected T_FROM and found T_ID(author)
```

**Comment by filhodanuvem** [comment]
Hey @tiberiuana , thank you for let us know. 
I just fixed that in a version `2.2.0`, can you please check that?

**Comment by tiberiuana** [comment]
It works for me now. Thanks for the quick reply! :rocket: 

I'm curious, since I see no new commits on main -- was the code already there but not in the binary release?

**Comment by filhodanuvem** [comment]
Yes, exactly that 😁. I might be missed the timing on creating a new release after a bunch of changes in the last hacktoberfest.
