### ISSUE TITLE
Set Up Dependabot

### ISSUE THREAD

**Issue by gabriellopes00** [filhodanuvem/gitql#119]
What's up, dude ? What do you think of setting up dependabot on this repository? Dependabot is a GitHub bot that checks dependency updates from repositories and, as any new version of a dependency appears, the bot automatically opens a new PR suggesting the update. It's secure because nothing is automatically deployed, so no updates will be able to compromise the app.  To set up it, you just need to configure this in the repository `settings` tab, and create a `dependabot.yml` file inside `.github` folder, with the bot specs, what do u think? Can I provide this file?

**Comment by gabriellopes00** [comment]
Dependabot is also compatible with many package managers from many different languages, and gomod is one of them.

**Comment by filhodanuvem** [comment]
Hey Gabriel, that's an awesome idea. I've enabled the bot on settings, feel free to send a minimal `dependabot.yml` :)

**Comment by gabriellopes00** [comment]
Thanks very much for accepting my contribution, @filhodanuvem 👊

**Comment by filhodanuvem** [comment]
Thank you for the help.
