### ISSUE TITLE
Refactor: Change visibility of methods, structs and variables 

### ISSUE THREAD

**Issue by filhodanuvem** [filhodanuvem/gitql#129]
In golang, every identifier which starts with a uppercase letter is visible outside of the package. There are a lot of exported variables/methods/structs in gitql that should be visibile only inside the package.

**Comment by marlonemmerich** [comment]
Hello, Claudson!
I'm sorry, i'm little late hahah
Can you check my PR if it's what you have in mind?
https://github.com/filhodanuvem/gitql/pull/138

If you have any suggestions, please, let me know!
Thank you again for this opportunity!

**Comment by filhodanuvem** [comment]
All good there :) thank you
