### ISSUE TITLE
Features about "databases" 

### ISSUE THREAD

**Issue by filhodanuvem** [filhodanuvem/gitql#18]
Some notes to the future 

1) Show Databases

``` bash
show databases; 
```

is similar to 

``` bash
git branch -a 
```

or something like that. 

2) Change to another database 

``` bash
use develop 
```

is similar to 

``` bash
git checkout develop  
```

**Comment by sesam** [comment]
This looks like nice stuff, and at least "show databases" can be a possible #hacktoberfest task. Of course, adding "show databases" more or less means also committing to adding "use (branch)" at some future point. How about we create this as two ticket? Can we break it down even further?

**Comment by filhodanuvem** [comment]
That's fair enough for me @sesam. Breaking it into #106 and #107
