### ISSUE TITLE
Publish in software repos

### ISSUE THREAD

**Issue by jsixface** [filhodanuvem/gitql#63]
Is it possible to publish this as a software package in open source software repos like Debian / centos repos. People can discover and install this by using 
```
sudo apt install gitql
```
or 
```
sudo yum install gitql
```

**Comment by luizperes** [comment]
That would be a very good one @jsixface! I dont have much time right now but will try to do will when I get some time! Thanks!

**Comment by jsixface** [comment]
This is what I had in mind.
  - Homebrew for mac
  - Debian repo for `apt install`
  - Centos Extras Repo for `yum install`
  - Arch Repo

**Comment by jhirbour** [comment]
For homebrew: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by filhodanuvem** [comment]
Gitql is available on homebrew. 
I think it's better to have different issues for each software repo (apt-get, chocolately and so on) so I'm closing this and feel free to help us to give support for the other OS.
