### ISSUE TITLE
Publish in Homebrew

### ISSUE THREAD

**Issue by jsixface** [filhodanuvem/gitql#71]
Make `gitql` available through homebrew to be installed via command `brew install gitql` 
A sub-task of #63 

I'll start working on this first

**Comment by jsixface** [comment]
@cloudson if `libgit2`  library is already installed in the system, can we go ahead and build gitql directly with go build. Assuming the dynamic library path is setup.

**Comment by jsixface** [comment]
@cloudson I was trying a ask a question there :smiley:  . Trying to find out why the fork libgit2 and git2go was used rather than original repos. If tagging to a specific version is needed the new dependency manager in go can help.

**Comment by jsixface** [comment]
That makes sense. Yeah dep can solve the versioning issue and can stick to a specific tag. That way we make libgit2 a system dependency and have gitql as installable software.

**Comment by isaeef** [comment]
@cloudson is this still open , if yes would like to work on it

**Comment by cloudson** [comment]
@isaeef definetly it's open and we would love to get your help. 😊

**Comment by ankane** [comment]
Hey @filhodanuvem, I created a formula here: https://github.com/ankane/homebrew-core/blob/master/Formula/gitql.rb

However, it fails with:

```sh
error: "Invalid libgit2 version; this git2go supports libgit2 v0.27"
# error "Invalid libgit2 version; this git2go supports libgit2 v0.27"
  ^
1 error generated.
```

Is it possible to support the latest version of libgit2 (1.0.1)?

**Comment by renatosuero** [comment]
what about [use](https://goreleaser.com/customization/homebrew/) to release new version including homebrew?

**Comment by filhodanuvem** [comment]
First of all, thanks for the effor @ankane, I just notice your message now, so sorry for the late. 
Currently gitql depends of git2go, which uses the libgit2. It seems that git2go supports libgit2 1.0, so we could upgrate and check it.

**Comment by ankane** [comment]
Great, happy to test again once #94 is merged (fwiw, it looks like there are some references in the code to `cloudson/git2go` that aren't in the PR).

**Comment by filhodanuvem** [comment]
Just a question, in the formula, can we fixed the libgit2 to 1.0.1? I'm worried that in few months it will start breaking because in gitql is not going to require the latest version of git2go/libgit2.

**Comment by ankane** [comment]
Homebrew has a few versioned formula, but from my understanding, it's only for very popular packages (the current libgit2 formula always references the latest version). With the 1.0 release, all 1.x releases should be backward compatible according to the release notes:

> This is release v1.0 "Luftschloss", which is the first stabe release of
libgit2. The API will stay compatible across all releases of the same major
version.

**Comment by filhodanuvem** [comment]
@ankane we just made a change that remove the libgit2 dependency, if you are able to try again on homebrew that would be awesome. I'm closing #94 since it's not needed anymore.

**Comment by ankane** [comment]
@filhodanuvem works great. Will submit whenever a new release is out.

**Comment by filhodanuvem** [comment]
Done @ankane

**Comment by ankane** [comment]
Great, submitted: https://github.com/Homebrew/homebrew-core/pull/62091

**Comment by filhodanuvem** [comment]
Thank you so much @ankane

**Comment by ankane** [comment]
```sh
brew install gitql
```

is now available.

**Comment by filhodanuvem** [comment]
Amazing! Thanks a lot @ankane for the effort. I'm closing this.

**Comment by ankane** [comment]
np, thanks for updating the project to make it work.
